# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_remove_favorite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='favorite',
            name='permalink',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='favorite',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
