# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 19:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorites', '0003_auto_20170129_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='access_token',
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
