# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0006_auto_20170129_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_id', models.CharField(default='', max_length=100)),
                ('permalink', models.CharField(default='', max_length=250)),
                ('url', models.CharField(default='', max_length=250)),
                ('author', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Reddit Post',
                'verbose_name_plural': 'Reddit Posts',
            },
        ),
    ]
